Repository insightsengineering/teal.data, pull requests merged in 2024-01, with the labels that each got.

#243 remove any.missing parameter
  R/formatters_var_labels.R
Labels: core

#241 collate and improve docs
  R/formatters_var_labels.R
  man/col_labels.Rd
  man/col_relabel.Rd
Labels: core

#212 Linter cleanup `@refactor`
  .lintr
  NEWS.md
  R/zzz.R
  data-raw/data.R
Labels: core

#244 improve label functions
  R/formatters_var_labels.R
  man/col_labels.Rd
Labels: core

#246 Remove unused internal function `check_simple_name`
  R/utils.R
  man/check_simple_name.Rd
  tests/testthat/test-check_simple_name.R
Labels: core

#250 249 remove check for `datanames` parameter being a subset of `datanames(teal_data)` in `get_code(teal_data)`
  R/teal_data-get_code.R
  man/get_code-teal_data-method.Rd
  tests/testthat/test-get_code.R
Labels: core

#239 237 fix assign detection when object is passed as character
  R/utils-get_code_dependency.R
  tests/testthat/test-get_code.R
Labels: bug, core

#248 refining tags in documentation
  R/cdisc_data.R
  R/data.R
  R/default_cdisc_join_keys.R
  R/deprecated.R
  R/formatters_var_labels.R
  R/join_key.R
  R/join_keys-c.R
  R/join_keys-extract.R
  R/join_keys-names.R
  R/join_keys-parents.R
  R/join_keys-utils.R
  R/join_keys.R
  R/teal_data-class.R
  R/teal_data-show.R
  R/teal_data.R
  R/testhat-helpers.R
  R/utils-get_code_dependency.R
  R/verify.R
  man/TealData.Rd
  man/assert_compatible_keys.Rd
  man/assert_compatible_keys2.Rd
  man/assert_parent_child.Rd
  man/cdisc_data.Rd
  man/col_labels.Rd
  man/default_cdisc_join_keys.Rd
  man/join_key.Rd
  man/join_keys.Rd
  man/new_teal_data.Rd
  man/parents.Rd
  man/rADAE.Rd
  man/rADCM.Rd
  man/rADLB.Rd
  man/rADRS.Rd
  man/rADSL.Rd
  man/rADTR.Rd
  man/rADTTE.Rd
  man/rADVS.Rd
  man/teal_data.Rd
  man/verify.Rd
Labels: core

#254 Fix `extract_calls` for calls with `;`
  R/utils-get_code_dependency.R
  tests/testthat/test-get_code.R
Labels: core

#264 Append `testthat` prefix for `join_keys` tests
  DESCRIPTION
  tests/testthat/test-cdisc_join_keys.R
  tests/testthat/test-join_key.R
  tests/testthat/test-join_keys-c.R
  tests/testthat/test-join_keys-extract.R
  tests/testthat/test-join_keys.R
Labels: core

#266 265 fix issue for using code in `quote` function with `get_code`
  R/utils-get_code_dependency.R
  tests/testthat/test-get_code.R
Labels: core

#269 Revert quote detection from 265
  R/utils-get_code_dependency.R
  tests/testthat/test-get_code.R
Labels: core

#272 271 fix `assign` function detection for cases with more than 2 arguments
  R/utils-get_code_dependency.R
  tests/testthat/test-get_code.R
Labels: core

#268 267 fix `@linksto` tag with `eval()` in last line of the evaluated code for `get_code`
  R/utils-get_code_dependency.R
  tests/testthat/test-get_code.R
Labels: core

#263 261 multiple improvements to `get_code` function and it's documentation
  DESCRIPTION
  R/teal_data-get_code.R
  R/utils-get_code_dependency.R
  man/get_code-teal_data-method.Rd
  man/get_code.Rd
  tests/testthat/test-get_code.R
Labels: core

#276 251 update vignettes@main
  R/teal_data.R
  man/cdisc_data.Rd
  man/teal_data.Rd
  vignettes/teal-data-reproducibility.Rmd
  vignettes/teal-data.Rmd
Labels: core

#282 deprecate check
  R/cdisc_data.R
  R/teal_data.R
  man/cdisc_data.Rd
  man/teal_data.Rd
  tests/testthat/test-cdisc_data.R
Labels: core

#284 Response to comments from CRAN `0.4.0-rc2`
  DESCRIPTION
Labels: documentation, core
